### ISSUE TITLE
Since v1.0.14 → Error: Cannot find module 'browserslist'

### ISSUE THREAD

**Issue by davidesigner** [browserslist/update-db#36]
Hi there,

Since the new release (1.0.14), my team and myself have this error when we run `npx update-browserslist-db@latest`.

```shell
Latest version:     1.0.30001615
Installed version:  1.0.30001615
caniuse-lite is up to date
caniuse-lite has been successfully updated

Error: Cannot find module 'browserslist'
Require stack:
- /Users/xxxx/.npm/_npx/2662cbd72e57abb6/node_modules/update-browserslist-db/index.js
- /Users/xxxx/.npm/_npx/2662cbd72e57abb6/node_modules/update-browserslist-db/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at getBrowsers (/Users/xxxx/.npm/_npx/2662cbd72e57abb6/node_modules/update-browserslist-db/index.js:78:22)
    at updateDB (/Users/xxxx/.npm/_npx/2662cbd72e57abb6/node_modules/update-browserslist-db/index.js:273:15)
    at Object.<anonymous> (/Users/xxxx/.npm/_npx/2662cbd72e57abb6/node_modules/update-browserslist-db/cli.js:34:5)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)

Problem with browser list retrieval.
Target browser changes won’t be shown.
```

**Comment by ai** [comment]
1. What package manager do you use?
2. Do you have Browserslists in your lock file?
3. Do you use monorepo?

**Comment by ai** [comment]
Why do you need `caniuse-lite` if you don’t have Browserslist?

**Comment by ai** [comment]
Very strange, we call `browserslist` in `try-catch` and ready for error from `require()`.

What is Node.js version?

**Comment by ai** [comment]
Seems like `update-browserslist-db` doesn’t see `browserslist` because it was run from temporary dir.

But I have no idea why this code is not working https://github.com/browserslist/update-db/blob/main/index.js#L274-L276

Do you have any way to reproduce the problem and debug it?

**Comment by davidesigner** [comment]
You can do that: `npx create-remix@latest --template remix-run/indie-stack` to install a new Remix project that have the problem:

<img width="656" alt="Screenshot 2024-05-02 at 16 55 43" src="https://github.com/browserslist/update-db/assets/13423202/341304f7-d4cd-42e5-bdf2-d9efeecb9ddd">

Then, just go to the project repository and run: `npx update-browserslist-db@latest`.

**Comment by ai** [comment]
It was not an error (the exit code was `0`), just a warning. 

But I improve the text https://github.com/browserslist/update-db/commit/1f3ab06d79cfee9d8944a9379f1d15dad9a83a28
